package Hibernate;
// Generated Apr 10, 2017 12:14:36 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * File generated by hbm2java
 */
public class File  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String title;
     private String description;
     private String file;
     private float rating;
     private Date date;

    public File() {
    }

    public File(String username, String title, String description, String file, float rating, Date date) {
       this.username = username;
       this.title = title;
       this.description = description;
       this.file = file;
       this.rating = rating;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }
    public float getRating() {
        return this.rating;
    }
    
    public void setRating(float rating) {
        this.rating = rating;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


